name: Cancel ongoing action

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

# This allows a subsequently queued workflow run to cancel previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  party:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v3.4.1

      - name: Install lolcatjs
        run: npm install --no-save lolcatjs

      - name: Run lolcatjs
        run: ./node_modules/.bin/lolcatjs --help

      - name: Sleep for a long time
        run: sleep 31

      - name: Sleep again
        run: sleep 32

      - name: Sleep one last time
        run: sleep 33
