name: Celebrate changed files

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  find-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3.6.0
        with:
          # Needed to detect changed files
          fetch-depth: 2

      - name: Get updated docs
        if: ${{ github.event_name == 'push' }}
        id: changed-files
        uses: tj-actions/changed-files@54849deb963ca9f24185fb5de2965e002d066e6b # pin @v37.0.5
        with:
          fetch_depth: 2
          files: docs/**/*.{md,mdx}
          files_ignore: docs/news/_template.md
          json: true

      - name: Debug what files changed
        env:
          FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #ROOT: ../../..
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: echo "${FILES}"
