name: Don't create branches that already exist

on:
  push:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  create-branch-maybe-baby:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3



      - name: The bug
        run: |

          git config --global user.name "docubot"
          git config --global user.email "67483024+docubot@users.noreply.github.com"

          branchname=openapi-is-great

          # Edit this very file here
          echo "# Ignore this" >> .github/workflows/dont-create-branches-that-already-exist.yml

          branchCheckout=$(git checkout -b $branchname)
          if ! [[ $? -eq 0 ]]; then
            echo "Branch $branchname already exists in `github/docs-internal`. Exiting..."
            exit 0
          fi
          git add .
          git commit -m "Add decorated OpenAPI schema files"
          git push origin $branchname

      - name: Install lolcatjs
        run: npm install --no-save lolcatjs

      - name: Run lolcatjs
        run: ./node_modules/.bin/lolcatjs --help
