name: Post PR comment with pictures

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  post-comment-with-pictures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: .github/screenshots/

      - uses: actions/github-script@v6
        id: figuring-out-what-to-say
        with:
          script: |
            const fs = require('fs')
            console.log(fs.readdirSync('.github/screenshots/'))

      - name: Debug output
        run: echo "${{ steps.figuring-out-what-to-say.outputs.result }}"

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Right now it's ${new Date()}`
            })
