name: Preview deploy

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Should we include translations?
        uses: actions/github-script@v6
        id: translations
        with:
          script: |
            const { owner, repo } = context.repo
            console.log(`The owner of ${repo} is ${owner}`)
            return Math.random() > 0.5

      - name: Get result
        run: echo "${{ steps.translations.outputs.result }}"

      - name: DON'T do it?
        if: ${{ steps.translations.outputs.result == 'false' }}
        run: echo "Don't do it"

      - name: DO it?
        if: ${{ steps.translations.outputs.result == 'true' }}
        run: echo "Do it"
