name: Scrape and index

on:
  workflow_dispatch:
  schedule:
    - cron: '*/4 * * * *'

# permissions:
#   contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref }}'
  cancel-in-progress: true


jobs:
  scrape-and-index:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        language: [en, ja, es]
    steps:
      - name: Sleep a little
        run: sleep 10
      - name: Be sensitive
        uses: actions/github-script@v6
        with:
          script: |
            if (Math.random()> 0.9) throw new Error("Crash!")
