name: Scrape and index

on:
  workflow_dispatch:
  schedule:
    - cron: '*/4 * * * *'
  workflow_run:
    workflows: ['Build and Deploy stuff']
    types:
      - completed

# permissions:
#   contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref }}'
  cancel-in-progress: true


jobs:
  scrape-and-index:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        language: [en, ja, es]
    steps:

      - name: Only if started on workflow_dispatch
        if: github.event.action == 'completed'
        run: echo "yes it was run because of a repository_dispatch"

      - name: Happy if parent workflow is happy
        if: github.event.action == 'completed'
        env:
          CONCLUSION: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo ${{ env.CONCLUSION }}

      - name: Sad if parent workflow is sad
        if: github.event.action == 'completed'
        env:
          CONCLUSION: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: echo ${{ env.CONCLUSION }}

      - name: Debug event 0
        run: echo '${{ toJSON(github.event) }}'

      - name: Debug event
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const event = JSON.parse(fs.readFileSync(process.env["GITHUB_EVENT_PATH"]));
            console.log(JSON.stringify(event, null, 2));

      - name: Sleep a little
        run: sleep 10
      - name: Be sensitive
        uses: actions/github-script@v6
        with:
          script: |
            if (Math.random()> 0.95) throw new Error("Crash!")
