name: Send after Build

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'Build and Deploy stuff'
    branches:
      - main
    types:
      - completed

# permissions:
#   contents: read

jobs:
  precondition:
    runs-on: ubuntu-latest
    outputs:
      precondition: ${{ steps.check.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: check
        with:
          script: |
            if (context.eventName === "workflow_dispatch") {
              return true;
            } else if (context.eventName === 'workflow_run') {
              return context.payload.workflow_run.conclusion === 'success';
            }
            console.log(context);
            throw new Error("Unable to find a reason");
      - name: Debug output
        run: echo "${{ steps.check.outputs.result }}"

  debugger:
    needs: precondition
    runs-on: ubuntu-latest
    steps:
      - name: What was the output?
        run: echo "${{ needs.precondition.outputs.result }}"
      # - name: What was the output from JSON?
      #   run: echo "${{ fromJSON(needs.precondition-check.outputs.result) }}"
      - name: All output?
        run: echo "${{ toJSON(needs.precondition.outputs) }}"

  build:
    needs: precondition
    if: ${{ needs.precondition.outputs.result == 'true' }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v3

      - name: Install lolcatjs
        run: npm install --no-save lolcatjs

      - name: Run lolcatjs
        run: ./node_modules/.bin/lolcatjs --help

  was_empty:
    needs: precondition-check
    if: ${{ needs.precondition.outputs.result == '' }}
    runs-on: ubuntu-latest
    steps:

      - name: Nothing
        run: echo "It was empty"
