name: Test some NextJS app

on:
  pull_request:

permissions:
  contents: read

jobs:
  warm-up:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: some-nextjs-app/package-lock.json

      - name: Install dependencies
        working-directory: some-nextjs-app
        run: npm ci

      - name: Cache nextjs build
        uses: actions/cache@v3
        with:
          path: some-nextjs-app/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('some-nextjs-app/package*.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Cache whole all the things
        uses: actions/cache@v3
        with:
          path: |
            some-nextjs-app/node_modules
            some-nextjs-app/.next/cache
          key: ${{ runner.os }}-node_modules-${{ hashFiles('.github/workflows/test-some-nextjs-app.yml') }}


  test-some-nextjs-app:
    needs: warm-up
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ['tom', 'dick', 'harry']
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: some-nextjs-app/package-lock.json

      - name: Restore all cache
        id: cached-all
        uses: actions/cache@v3
        with:
          path: |
            some-nextjs-app/node_modules
            some-nextjs-app/.next/cache
          key: ${{ runner.os }}-node_modules-${{ hashFiles('.github/workflows/test-some-nextjs-app.yml') }}

      - name: Debug cached-all?
        run: echo "${{ steps.cached-all.outputs.cache-hit }}"

      - name: Freak out?
        if: ${{ steps.cached-all.outputs.cache-hit != 'hit' }}
        run: |
          echo "Everybody freak out"
          exit 1

      - name: Stay cool?
        if: ${{ steps.cached-all.outputs.cache-hit == 'hit' }}
        run: |
          ls -l
          ls -l some-nextjs-app
          du -sh some-nextjs-app/node_modules
          du -sh some-nextjs-app/.next/cache


      # - name: Install dependencies
      #   working-directory: some-nextjs-app
      #   run: npm ci

      # - name: Cache nextjs build
      #   uses: actions/cache@v3.2.3
      #   with:
      #     path: some-nextjs-app/.next/cache
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('some-nextjs-app/package*.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-

      # - name: Run build script
      #   working-directory: some-nextjs-app
      #   run: npm run build

      - name: Start in background
        working-directory: some-nextjs-app
        env:
          PORT: 3000
        run: npm run start &

      - name: Test with curl
        run: curl --retry-connrefused --retry 3 http://localhost:3000 > /dev/null

      - name: View by name
        run: curl http://localhost:3000/${{ matrix.name }}
