name: Upload build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Make something
        run: |
          mkdir buildstuff
          dd if=/dev/zero of=buildstuff/big.file count=1024 bs=1024
          echo 'This file is empty' > buildstuff/file.txt
          echo '' >> buildstuff/file.txt
          zip -r buildstuff.zip buildstuff

      - uses: actions/upload-artifact@v3
        with:
          name: buildstuff
          path: buildstuff.zip

      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PETERBECOM_DISPATCH }}
          repository: peterbe/django-peterbecom
          event-type: ping
          # client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
