name: Upload build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Make something
        run: |
          mkdir buildstuff
          echo 'This file is empty' > buildstuff/file.txt
          echo '' >> buildstuff/file.txt

      - uses: actions/upload-artifact@v3
        with:
          name: buildstuff
          path: buildstuff
